### ISSUE TITLE
search with 2 words keyword? 

### ISSUE THREAD

**Issue by arunbabucode** [spatie/laravel-searchable#10]
I have a user model with `first_name` and `last_name`. If I search the keyword `first_name` or `last_name` works fine. But is it possible to match by searching the full name? 

Ex: John is `first_name`, Doe is the `last_name`. If I search 'John' or 'Doe' it's returning as properly as expected. But if my keyword is 'John Doe', it's returning empty.

**Comment by larsjanssen6** [comment]
@arunbabucode here you go :)

**Comment by freekmurze** [comment]
We'll handle this further in #11
