### ISSUE TITLE
Pass ->search() method array of key words?

### ISSUE THREAD

**Issue by nickbluestone98** [spatie/laravel-searchable#125]
Cannot seem to find a way to pass an array of keywords to this package?

```
//Ideally this would be perfect...
 $search_results = (new Search())
            ->registerModel(Category::class, ['name'])
            ->search(['Sound', 'Video', 'Media']);
```

**Comment by agostinofiscale** [comment]
Hi @nickbluestone98, probably you don't need this information anymore but maybe it can help someone else!

The term that you pass to search method gets splitted by spaces, so if you need to pass any array you can just implode it using a space as separator.

**Comment by AlexVanderbist** [comment]
Hey @nickbluestone98, you're right; this package currently doesn't support searching for an array of strings. I'm not sure how this would work either (queries for all values with AND conditions or OR conditions?). Feel free to PR something like this!
