### ISSUE TITLE
Eager loading relationship

### ISSUE THREAD

**Issue by Livijn** [spatie/laravel-searchable#14]
I think it would be great if one could somehow eager load relationship with this package. Right now, it creates an N+1 problem.

**Comment by dinajpuri** [comment]
Please!

**Comment by dinajpuri** [comment]
+1

**Comment by AlexVanderbist** [comment]
You can using custom search aspects! Take a look at https://github.com/spatie/laravel-searchable/issues/8#issuecomment-454052880.

Hopefully this is what you were looking for?

**Comment by Livijn** [comment]
That is true, it does suffice.
