### ISSUE TITLE
Snippets Feature Request

### ISSUE THREAD

**Issue by z-h-z-h** [spatie/laravel-searchable#17]
Like this:
![2019-01-21_11-40-43](https://user-images.githubusercontent.com/344355/51457011-87e5b900-1d71-11e9-9fa9-4070c250929c.png)

**Comment by freekmurze** [comment]
Rendering specific html is out of scope for this package. You should [render the html yourself](https://github.com/spatie/laravel-searchable#rendering-search-results).
