### ISSUE TITLE
Pagination on search results

### ISSUE THREAD

**Issue by evc94** [spatie/laravel-searchable#20]
It would be awesome, if the results on searchable query provide a function just like `->paginate(int)` on collections to be more effective when the search has multiple models.

**Comment by SaphiLC** [comment]
any news? or at least any reply from the team saying "no" or "not at the moment" or the classic "make a PR" instead of giving the feeling this project is dead? thanks

**Comment by judgej** [comment]
So if a search term matches 1,000,000 records, does this package return 10,000,000 records in a collection? If so, it does not seem very practical.

**Comment by freekmurze** [comment]
Pagination is not supported by default in the model aspect class. If you want pagination you can implement [your own custom search aspect](https://github.com/spatie/laravel-searchable#creating-custom-search-aspects).

I'd accept a PR with tests and an updated readme that adds pagination to `ModelSearchAspect`.

**Comment by bytebrain** [comment]
I use https://github.com/spatie/laravel-collection-macros#paginate to paginate the search results collection.

**Comment by judgej** [comment]
That operates on a collection, which I guess means it has all been selected into memory. That's not really how a pager should work IMO.

**Comment by bytebrain** [comment]
I agree, it's really slow on large data sets, but it was a solution on my project.

**Comment by lloricode** [comment]
Return class type `Spatie\SearchableSearchResultCollection` has inherit class `Illuminate\Support\Collection`, so meaning this already a [forPage](https://laravel.com/docs/5.8/collections#method-forpage) from parent class

so now we can use 
```php
        $results= app(\Spatie\Searchable\Search::class)
            ->registerModel(\App\Product::class,  [
                'title',
                'content',
                'segment',
                'slug',
            ])
            ->search($request->input('key'));

        return $results->forPage(1,10);
```

**Comment by notflip** [comment]
Is it possible to write your own pagination code on the query builder that is, paginating on the Collection is useless, as stated above.

**Comment by nathanael79** [comment]
@bytebrain hi bytebrain, can you show me your code how to implement pagination? i really need that, thanks

**Comment by nathanael79** [comment]
is there any example about how to use pagination and create custom aspect? i still doesnt understand well when i read the readme.md @judgej

**Comment by JunaidQadirB** [comment]
If anyone is looking for pagination with their search results (which is obvious), then check out this package
[Laravel Cross Eloquent Search](https://github.com/protonemedia/laravel-cross-eloquent-search).
