### ISSUE TITLE
Enable Package Discovery?

### ISSUE THREAD

**Issue by WyattCast44** [spatie/laravel-searchable#24]
Greetings!

Just wanted to see if your open to a pull request to enable package auto discovery? If not, no big deal. 

Cheers,
- Wyatt

**Comment by freekmurze** [comment]
There's nothing to discover 😄 we don't have a service provider or facade in this package.

**Comment by WyattCast44** [comment]
Ah! Dang it, my bad! 😵 

Thanks, have a great week!
