### ISSUE TITLE
is it possible to display eager loading result

### ISSUE THREAD

**Issue by Nagraj137** [spatie/laravel-searchable#26]
I want to display has many relationship results. 

i have a tables "authors" and "articles" with belongsToMany relation.

if I search with author name, should display the related articles ( one author can writes many articles  ).  

i have tried with custom search aspects but not succeed. got the below error 

Declaration of App\ContributorSearch::getResults(string $term): App\Collection must be compatible with Spatie\Searchable\SearchAspect::getResults(string $term): Illuminate\Support\Collection

**Comment by bytebrain** [comment]
You are missing:
```
use Illuminate\Support\Collection;
```
In your `ContributorSearch` class
