### ISSUE TITLE
use GroupByType with vue js

### ISSUE THREAD

**Issue by BechirAhmed** [spatie/laravel-searchable#27]
How to group results by Type when use vue js and axios to search and fetch results?

**Comment by BechirAhmed** [comment]
Actually i found the answer, I won't delete the issue, maybe will help someone else
Lodash has an aptly named function called groupBy which we could use:
```
function groupBy(array, key){
  const result = {}
  array.forEach(item => {
    if (!result[item[key]]){
      result[item[key]] = []
    }
    result[item[key]].push(item)
  })
  return result
}
```

then use it like:
```
computed:{
  groups(){
    return groupBy(this.list, 'groupName')
  }
}
```

Then in your template:
```
<div v-for="group, groupName in groups">
  <h2>{{groupName}}</h2>
  <pre v-for="item in group">{{item}}</pre>
</div>

**Comment by TechTailor** [comment]
Hey, for some reason this doesnt seem to be working for my setup. Would appreciate a hand.
PS> Using Laravel 6.x

**Comment by BechirAhmed** [comment]
@TechTailor could you please add more explanation, like how you implement this and show some code
