### ISSUE TITLE
Problem with search string...

### ISSUE THREAD

**Issue by vksco** [spatie/laravel-searchable#28]
I have registered model to being searchable throw the string. An example I have two users name 'JOHN NILSON' & 'DOE NILSON' when I am typing a single word in search area like 'john 'then its return JOHN, perfect results, but when I use spaces in search string like 'john doe' then it is returning both JOHN & DOE.
as per my query, I need only the results with JOHN DOE.
how can it be done?

**Comment by EdvardasP** [comment]
Hello,
You can achieve this by creating custom search aspect:
https://github.com/spatie/laravel-searchable#creating-custom-search-aspects
In your case could be:
  ```
public function getResults(string $term): Collection
{
   return User::where('name', 'LIKE', "%{$term}%")->get();
 }
```
