### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by rzfortes** [spatie/laravel-searchable#29]
hi. is it possible to fix this without upgrading to laravel 5.8? 

![image](https://user-images.githubusercontent.com/22534337/57296637-076c7d80-7100-11e9-8223-14a1bea30a8d.png)

**Comment by rzfortes** [comment]
sorry about this. I installed it already by specifying a version release. Thank you

**Comment by DeanWard** [comment]
In case anyone else is facing this issue you can specify 1.2.3 to get the latest version that supports Laravel 5.7
