### ISSUE TITLE
Search on Json fields

### ISSUE THREAD

**Issue by Yarandi** [spatie/laravel-searchable#30]
Hi, 
I have an issue with searching on json fields, 

```
$searchResults = (new Search())
            ->registerModel(Document::class, ['title', 'body', 'sender->title'])
            ->registerModel(Inbox::class, 'document_reference')
            ->perform($search);
```

> sender is a field that have a property named title and I want search on it, 

How should i do this? did you handle json search ?

Thanks in advance

**Comment by AlexVanderbist** [comment]
Hi, I would use a custom search aspect for some finer grained control over the search query: https://github.com/spatie/laravel-searchable#creating-custom-search-aspects

It would look something like this:
```php
class DocumentSearchAspect extends SearchAspect
{
    public function getResults(string $term): Collection
    {
        return Document::where('title', $term)->orWhere('body', $term)->orWhere('sender->title', $term);
    }
}
```

You would use it like this:

```php
$searchResults = (new Search())
   ->registerAspect(DocumentSearchAspect::class)
   ->search('john');
```

Good luck and feel free to open a new issue if you have any more questions
