### ISSUE TITLE
Search Model on Appended Attribute

### ISSUE THREAD

**Issue by ashniazi** [spatie/laravel-searchable#32]
Hey guys,

Love the package. Question I had was whether it was possible to add a custom attribute based on a function that's not in the database.

example my Query Model has a body column which contains JSON markup for the delta text rendering. Basically it's a mix of text and transformations like this:

Query::class body column.
```
{"ops":[{"insert":"No power again as of 5pm\n"}]}
```

so say I were to register the Model, and I wanted to search the body for the word power. I'd do:

```
$results = (new Search())->registerModel(Query::class, 'body')->search($request->input('query'));
```
And that would work. However If someone were to search for the word 'insert' or something that is part of the delta syntax, it would include that in the search result. 

So I have a function in my Query class called `getDeltaStringAttribute()` that returns the delta body in text (without the transformations). In my Query model I added 'deltaString' to my `protected $appends = []` array. 

Meaning in ticker and usual object references I can get call `$query->deltaString;` and instead of getting `{"ops":[{"insert":"No power again as of 5pm\n"}]}` I would get `No power again as of 5pm`.

Now since this column / attribute doesn't technically exist, how can I register that in my search? 
```
->registerModel(Query::class, 'deltaString')
```
would not work in this fashion.

Any idea if this is possible or if I can extend it someone?

Thank you!

**Comment by AlexVanderbist** [comment]
Hi!

The `registerModel` method is only able to query basic database columns (int/text/datetime/...). If you need anything more advanced, I would propose custom search aspects: https://github.com/spatie/laravel-searchable#creating-custom-search-aspects.

You could create a custom "QuerySearchAspect" that uses json where clauses (https://laravel.com/docs/master/queries#json-where-clauses).

It would look something like this:
```php
class QuerySearchAspect extends SearchAspect
{
    public function getResults(string $term): Collection
    {
        return Query::where('body->ops->insert', $term);
    }
}
```

Querying directly on the `deltaString` attribute you added is not possible. Those attributes are only parsed and added when getting the model. Getting all models to look for the custom attribute getter would be really bad for perfomance ;)

Good luck and feel free to create a new issue if you're having problems.
