### ISSUE TITLE
Searching in numeric fields with PostgreSQL throws an exception with LOWER() function

### ISSUE THREAD

**Issue by Metalgrid** [spatie/laravel-searchable#34]
Hello,
Using `spatie/laravel-searchable` version `1.3.0` with PostgreSQL 11, I'm getting an exception `SQLSTATE[42883]: Undefined function: 7 ERROR:  function lower(bigint) does not exist`.
MySQL allows using `lower` on integers but PostgreSQL has strict typing on its functions and the only prototype is `lower(text)`. Is it possible to typecheck the field and use `lower` only where it makes sense?

**Comment by freekmurze** [comment]
Feel free to submit a non breaking PR with tests.
