### ISSUE TITLE
use this with strict match result

### ISSUE THREAD

**Issue by fredattack** [spatie/laravel-searchable#35]
hello, 

Is it possible to use this with strict matching results :
exemple: 
User::where('name', '=', "%{$term}%")->get();

instead of this:
User::where('name', 'LIKE', "%{$term}%")->get();

thanks

**Comment by vdbelt** [comment]
Omit the % character. It serves as a wildcard. 

Not sure how your question relates to this package. If you want to implement exact match searches with laravel-searchable, see the [README](https://github.com/spatie/laravel-searchable#searching-models) for an example.
