### ISSUE TITLE
Additional Search Condition

### ISSUE THREAD

**Issue by ideadx** [spatie/laravel-searchable#37]
Not sure if already supports but couldn't find in the doc: Way to get Search records where active is 1? 

Example: 

$results = (new \Spatie\Searchable\Search())
        ->registerModel(Listing::class, 'name')
        ->search($terms);

How do I add condition (if any)?
Thanks.

**Comment by vdbelt** [comment]
You could create a custom search aspect. 

See https://github.com/spatie/laravel-searchable/issues/9#issuecomment-454054653 for an example.
