### ISSUE TITLE
Searching the model and relations

### ISSUE THREAD

**Issue by hanynasyr** [spatie/laravel-searchable#46]
Is it possible to search the model and the relations of the model?
for example:
Search term = "Red T-Shirt"
Model: Product
Relations: Categories, tags
search columns product.name, Categories.name and tags.name

**Comment by rcubitto** [comment]
Adding searchable attributes to a relationship is not natively supported. 

You could try being explicit on how to search inside the relationships.
```php
$term = 'Red T-Shirt';

$search = (new Search())
    ->registerModel(Product::class, function(ModelSearchAspect $modelSearchAspect) use ($term) {
        $modelSearchAspect
            ->addSearchableAttribute('name')
            ->orWhereHas('categories', function ($query) { $query->whereRaw('LOWER(name) like %'  . mb_strtolower($term, 'UTF8') . '%')
            ->orWhereHas('tags', function ($query) { $query->whereRaw('LOWER(name) like %'  . mb_strtolower($term, 'UTF8') . '%')
})->search($term);
```

**Comment by hanynasyr** [comment]
That might work... Will give it a try.. Thanks rcubitto.

**Comment by iamB0rgy** [comment]
I'm having an error `Undefined variable $term`. $term is defined above it.

**Comment by iamB0rgy** [comment]
> > Adding searchable attributes to a relationship is not natively supported.
> > You could try being explicit on how to search inside the relationships.
> > ```
> > $term = 'Red T-Shirt';
> > 
> > $search = (new Search())
> >     ->registerModel(Product::class, function(ModelSearchAspect $modelSearchAspect) use ($term) {
> >         $modelSearchAspect
> >             ->addSearchableAttribute('name')
> >             ->orWhereHas('categories', function ($query) { $query->whereRaw('LOWER(name) like %'  . mb_strtolower($term, 'UTF8') . '%')
> >             ->orWhereHas('tags', function ($query) { $query->whereRaw('LOWER(name) like %'  . mb_strtolower($term, 'UTF8') . '%')
> > })->search($term);
> > ```
> 
> The above code works if you fix the syntax issues 👍, thanks @freekmurze

@seewhy17 , I am getting $term error. Can you show here the correct one?
