### ISSUE TITLE
ELASTICSEARCH

### ISSUE THREAD

**Issue by lalitvohra** [spatie/laravel-searchable#50]
how can we implement elasticsearch with this ?

**Comment by AlexVanderbist** [comment]
Create custom search aspect that fetches search results from Elastic: https://github.com/spatie/laravel-searchable#creating-custom-search-aspects.

However, if you're just looking for an elasticsearch solution, you might be better of with another package.

If you need any help with creating that custom search aspect, feel free to open a new issue 👍

**Comment by dlr-delarocha** [comment]
@lalitvohra  This package is not to use Elastic search, Elastic require a more robust package, but if u want to create a custom search with this package check this example:

https://github.com/dlr-delarocha/searchable-trigrams
