### ISSUE TITLE
Struggling with aspects

### ISSUE THREAD

**Issue by ju5t** [spatie/laravel-searchable#53]
I am trying to come up with a solution for the `explode()` happening in ModelSearchAspect's addSearchConditions(). I would like to search for 'hello world' instead of 'hello' and 'world' which is the current functionality.

I tried creating my own aspect.

```php
<?php

namespace App\Search;

use Illuminate\Database\Eloquent\Builder;
use Spatie\Searchable\ModelSearchAspect;

class FullSearchAspect extends ModelSearchAspect
{
    protected function addSearchConditions(Builder $query, string $term)
    {
        $attributes = $this->attributes;

        $query->where(function (Builder $query) use ($attributes, $term, $searchTerms) {
            foreach (Arr::wrap($attributes) as $attribute) {
                $sql = "LOWER({$attribute->getAttribute()}) LIKE ?";
                $searchTerm = mb_strtolower($term, 'UTF8');

                $attribute->isPartial()
                    ? $query->orWhereRaw($sql, ["%{$term}%"])
                    : $query->orWhere($attribute->getAttribute(), $term);
            }
        });
    }
}
```

And the following snippet is responsible for search:

```php
class SearchController extends Controller
{
    public function search(Request $request, $search)
    {
        $searchResults = (new Search())
            ->registerAspect(FullSearchAspect::class)
            ->registerModel(Article::class, function (FullSearchAspect $modelSearchAspect) {
```

This gives me an error:

```
Unresolvable dependency resolving [Parameter #0 [ <required> string $model ]] in class Spatie\Searchable\ModelSearchAspect
```

I guess this happens because I don't understand aspects yet. I _think_  I need to override Search() too and override `registerModel` to use my aspect (or add a new method).

What do you suggest?

**Comment by AlexVanderbist** [comment]
Hm, I think you're probably best just creating an entirely new custom search aspect (without extending from the ModelSearchAspect): https://github.com/spatie/laravel-searchable#creating-custom-search-aspects

It's been a while since I looked at this package in detail but I think you'll get better results when implementing the `getResults` method, instead of the `addSearchConditions`.

**Comment by ju5t** [comment]
The underlying issue for us is the fact that `registerAspect` doesn't take additional arguments. It expects that the aspect knows it all, where we only wanted to modify the behaviour of the `ModelSearchAspect`.

In the end it would be better to make `registerAspect` accept optional arguments but from a time perspective this was the quickest.

```php
<?php

namespace App\Search;
use Illuminate\Support\Arr;
use Spatie\Searchable\Search as BaseSearch;

class Search extends BaseSearch
{
    public function registerFullSearchModel(string $modelClass, ...$attributes) : BaseSearch
    {
        if (isset($attributes[0]) && is_callable($attributes[0])) {
            $attributes = $attributes[0];
        }

        if (is_array(Arr::get($attributes, 0))) {
            $attributes = $attributes[0];
        }

        $searchAspect = new FullSearchAspect($modelClass, $attributes);

        $this->registerAspect($searchAspect);

        return $this;
    }
}
```

And:

```php
<?php

namespace App\Search;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Arr;
use Spatie\Searchable\ModelSearchAspect;

class FullSearchAspect extends ModelSearchAspect
{
    protected function addSearchConditions(Builder $query, string $term)
    {
        $attributes = $this->attributes;

        $query->where(function (Builder $query) use ($attributes, $term) {
            foreach (Arr::wrap($attributes) as $attribute) {
                $sql = "LOWER({$attribute->getAttribute()}) LIKE ?";
                $searchTerm = mb_strtolower($term, 'UTF8');

                $attribute->isPartial()
                    ? $query->orWhereRaw($sql, ["%{$term}%"])
                    : $query->orWhere($attribute->getAttribute(), $term);
            }
        });
    }
}
```

And we use `registerFullSearchModel` instead of `ModelSearchAspect` in our controller that does the search.

For a future version I think that `registerAspect` should accept optional arguments and that `ModelSearchAspect` should be capable of using `registerAspect` instead of having it's own function like it is at the moment.
