### ISSUE TITLE
syntax error, unexpected ')'  on Model Function

### ISSUE THREAD

**Issue by jefcoserrca** [spatie/laravel-searchable#54]
Hi, I used this library on my local project and it works but when I uploaded on a server i have this error :
**Symfony\Component\Debug\Exception\FatalThrowableError
syntax error, unexpected ')'**
`<?php

 

namespace App;

 

use Illuminate\Database\Eloquent\Model;

use Spatie\Searchable\Searchable;

use Spatie\Searchable\SearchResult;

 

class TusProgram extends Model implements Searchable

{

    public function getSearchResult(): SearchResult

    {

        return new \Spatie\Searchable\SearchResult(

            $this,
             program_name,
            '/academics/tus',

###         );

    }

}`

**Comment by freekmurze** [comment]
In your snippet I do see a syntax error. `program_name` should probably be surrounded by quotes.

**Comment by dfrey382** [comment]
> Hi, I used this library on my local project and it works but when I uploaded on a server i have this error :
> **Symfony\Component\Debug\Exception\FatalThrowableError syntax error, unexpected ')'**
> `<?php
> 
> namespace App;
> 
> use Illuminate\Database\Eloquent\Model;
> 
> use Spatie\Searchable\Searchable;
> 
> use Spatie\Searchable\SearchResult;
> 
> class TusProgram extends Model implements Searchable
> 
> {
> 
> ```
> public function getSearchResult(): SearchResult
> 
> {
> 
>     return new \Spatie\Searchable\SearchResult(
> 
>         $this,
>          program_name,
>         '/academics/tus',
> ```
> 
> ### );
> ```
> }
> ```
> 
> }`

I have the same error
