### ISSUE TITLE
Search Limit

### ISSUE THREAD

**Issue by Dozorov** [spatie/laravel-searchable#56]
Hi, any solutions to LIMIT serach request?

**Comment by shinuskn** [comment]
You can use the take() method.

Example:
`$modelSearchAspect->addSearchableAttribute('title')->orderBy('title', 'ASC')->take(10)`

**Comment by WalrusSoup** [comment]
Limit works there as well it seems:

```php
        $search = (new Search())->registerModel(ServiceRequest::class, function(ModelSearchAspect $modelSearchAspect) {
            $modelSearchAspect->addSearchableAttribute('title')
                ->limit(10);
        });
        return new ServiceRequestResource::collection(search->search($request->input('title')));
```

**Comment by freekmurze** [comment]
This is currently not possible. I'd accept a PR request that adds this to the package with tests and an updated readme.

**Comment by freekmurze** [comment]
@Dozorov @shinuskn what's your opinion on #82?
