### ISSUE TITLE
Prioritize results

### ISSUE THREAD

**Issue by pakogn** [spatie/laravel-searchable#57]
Hi,

the package is really useful, one of the features I was looking for was to split the term, etc... congratulations.

Have you thought on adding sort support, like put on top the most similar result to the term?

I would think like using similar_text or levenshtein PHP functions to achieve this.

**Comment by msslgomez** [comment]
I would also like to know if there is a way to do this. Currently the search works great but if I add an exact text I want it never returns the item that perfectly matches, it's always a bunch that are close but not it.
