### ISSUE TITLE
Backticks used in Spatie\Searchable\ModelSearchAspect::addSearchConditions() are not supported by PostgreSQL

### ISSUE THREAD

**Issue by shorlbeck** [spatie/laravel-searchable#62]
Queries containing backticks (`) work in MySQL to quote system identifiers, but they will cause PostgreSQL to choke. Example:

    select * from users where (LOWER(`full_name`) LIKE '%foo%' or /* ... */ )

Works in MySQL (presumably) but Postgres doesn't like this. Instead we get the following Exception:

    Illuminate/Database/QueryException with message 'SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: ` character varying
    LINE 1: select * from "users" where (LOWER(`full_name`) LIKE $1 or L...
                                               ^
    HINT:  No operator matches the given name and argument type. You might need to add an explicit type cast. (SQL: select * from "users" where (LOWER(`full_name`) LIKE %foo% or LOWER(`email`) LIKE %foo%) and "users"."deleted_at" is null)'

The main place I found this issue was in `Spatie\Searchable\ModelSearchAspect::addSearchConditions()` but it could be elsewhere in the code since I'm not familiar with it.

I'd like to recommend that this package accept a `$connection` parameter to specify which database connection to use (e.g. `new Search($connection)`,  which would default to `config('database.default')` if not given). Then, the above-mentioned method can decide to use backticks if the connection driver is `'mysql'` and double-quotes if the connection driver is `'pgsql'`. (Not sure about other database vendors.)

**Comment by freekmurze** [comment]
Because I don't use Postgres, I'm not going to invest time in this. Feel free to create a fully tested and documented PR to add this. 

I'll merge it if the code is simple/clean enough.
