### ISSUE TITLE
Search polymorphic relations (tags)

### ISSUE THREAD

**Issue by Shi974** [spatie/laravel-searchable#66]
Hello ! I am using another great Spatie's package : [spatie/laravel-tags](https://github.com/spatie/laravel-tags)

As you may know, this package adds tags to the models, just like this, using polymorphic relationship : 

**Taggables**
- tag_id
- taggable_type
- taggable_id

**Tags**
- id
- name (json datatype for translations)
- slug
- type
[...]

I was wondering how to implement the search on models with tags ?
I tried using _ModelSearchAspect_, but I couldn't succeed. Any leads on how to make this work ?

Thanks by advance, and thanks to Spatie for these great packages ! 😁 👍

**Comment by freekmurze** [comment]
We currently don't have time to invest in this issue. If you find a good way, feel free to submit a PR with tests for us to review.
