### ISSUE TITLE
1.6.2 breaks search with PostgreSQL

### ISSUE THREAD

**Issue by JhumanJ** [spatie/laravel-searchable#68]
Hello,

It seems that 1.6.2 escaping change (https://github.com/spatie/laravel-searchable/compare/1.6.1...1.6.2) broke search with PostreSQL 10. Example error:

Sample error:
```
SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: ` character varying\nLINE 1: select * from \"restaurants\" where (LOWER(`name`) LIKE $1 or ...\n                                                 ^\nHINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts. (SQL: select * from \"restaurants\" where (LOWER(`name`) LIKE %mor% or LOWER(`email`) LIKE %mor% or LOWER(`phone`) LIKE %mor%) and \"restaurants\".\"deleted_at\" is null limit 5)",
```

Thanks for this package.

**Comment by dlr-delarocha** [comment]
@JhumanJ  see this https://github.com/spatie/laravel-searchable/issues/62, are you using PostgreSQL?

**Comment by freekmurze** [comment]
Closing as we don't use Postgresql ourselves. Feel free to submit a PR that fixes this. All tests should be green.
