### ISSUE TITLE
Q: Policies on models

### ISSUE THREAD

**Issue by ekandreas** [spatie/laravel-searchable#69]
Does the package respect Policies to filter the result?

**Comment by freekmurze** [comment]
I don’t know what you mean... could you give a concrete example? 

Please also refer to the readme to learn what this package can and cannot do.

**Comment by ekandreas** [comment]
Models can be extended with policies as standard in Laravel. 
If you dont have access to the data eloquent respects that. Is it the same in this package. 

Nevermind, perhaps I should setup a sample project and try it out.

**Comment by freekmurze** [comment]
No, this is somethings you should take care in the query. Even in vanilla Laravel, policies won't be respected when you are building up a query of your own.

**Comment by ekandreas** [comment]
Then we have different views on what function a policy has.

**Comment by groax** [comment]
I need the same thing. :)

**Comment by groax** [comment]
My fix

`if (Auth::user()->can('view', User::class)) {
            $searchResults[] = (new Search())
                ->registerModel(User::class, ['name', 'firstname', 'surname'])
                ->limitAspectResults($limit)
                ->search(str_replace(' ', '%', $request['searchInput']));
        }`
