### ISSUE TITLE
Code refactoring

### ISSUE THREAD

**Issue by emilas44** [spatie/laravel-searchable#75]
here:
https://github.com/spatie/laravel-searchable/blob/95ce9dc6cbb3206fd6c03258419f9a967b5dd05e/src/Search.php#L61

` $aspect->getResults($query, $user);`

uses 2 parameters but the method signature has only one!

**Comment by freekmurze** [comment]
Feel free to fix this by submitting a PR! Thanks!

**Comment by emilas44** [comment]
I don't fully understand the concept of why is there a $user variable at first place...
So it would be better if @AlexVanderbist could take a look at this
