### ISSUE TITLE
Searching related models

### ISSUE THREAD

**Issue by jerauf** [spatie/laravel-searchable#8]
Great package! Love it so far.

Is it possible to search related models? For example, a UserProfile model but search through User? I want to display the profile results as part of the search in the User type? In other words, I'd search user_biography in UserProfile but will want to display the results grouped in User results in case they search username.

Possible?

**Comment by AlexVanderbist** [comment]
Hi! 

Have a look at [creating custom search aspects](https://github.com/spatie/laravel-searchable#creating-custom-search-aspects) in the readme. Using custom search aspects you can use any code you like to perform a search.

For example, here's a custom search aspect that might help you out for your specific use case:

```php
class UserSearchAspect extends SearchAspect
{
    public static $searchType = 'User';

    public function getResults(string $term): Collection
    {
        return User::query()
            ->where('email', 'LIKE', "%{$term}%") // search for $user->email property
            ->orWhereHas('userProfile', function($query) use ($term) {
                // and search for $user->userProfile->username property
                $query->where('username', 'LIKE', "%{$term}%"); 
            })
            ->get();
    }
}
```
The `registerModel()` method in the readme is basically a helper to generate the above code for any model.

Hopefully this is what you were looking for?

**Comment by mrmmg** [comment]
@AlexVanderbist Hi, You said we must create a class, but where? which directory?
can you explain to me a little bit?

**Comment by santiagocarlos** [comment]
hi @mrmmg, did you know in which directory or where to create this class?
