### ISSUE TITLE
ModelSearchAspect getResults has param User but not SearchAspect

### ISSUE THREAD

**Issue by thewebartisan7** [spatie/laravel-searchable#80]
The  ModelSearchAspect::getResults() has  User $user = null as param, see https://github.com/spatie/laravel-searchable/blob/master/src/ModelSearchAspect.php#L96 but not the parent class SearchAspect that extend https://github.com/spatie/laravel-searchable/blob/master/src/SearchAspect.php#L10 

Seem also never used User $user, also not in doc I see the usage of it.

Is this a typo or I missed something?

Thanks

**Comment by freekmurze** [comment]
You're right, I've removed `$user`.
