### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by shevtsov-max** [spatie/laravel-searchable#89]
When will php 8 support?

**Comment by freekmurze** [comment]
When you submit the PR 👍  Make sure to make the tests run on PHP 8 as well.

**Comment by shevtsov-max** [comment]
What am I doing wrong?

root@c6459a6f04fe:/var/www# composer update

Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires spatie/laravel-searchable ^1.8 -> satisfiable by spatie/laravel-searchable[1.8.0].
    - spatie/laravel-searchable 1.8.0 requires php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.
