### ISSUE TITLE
Adding scope to filter search results

### ISSUE THREAD

**Issue by addorange** [spatie/laravel-searchable#9]
Hi spatie,

thanks for this nice package. Loving it so far.

But I wonder, if I could add a scope like published() to the search on posts. Is that possible? Could not find a way to apply it yet.

Best regards

Chris

**Comment by AlexVanderbist** [comment]
Hi @addorange ! 

Take a look at [creating custom search aspects](https://github.com/spatie/laravel-searchable#creating-custom-search-aspects) in the readme. Using custom search aspects you can basically use any code you like to perform a search.

For example, here's a custom search aspect that allows you to query a scope:

```php
class PostSearchAspect extends SearchAspect
{
    public static $searchType = 'Post';

    public function getResults(string $term): Collection
    {
        return Post::published($term)->get();
    }
}
```

The `registerModel()` method in the readme is merely a helper to generate the above code for any model.

Hopefully this is what you were looking for?

**Comment by jannejava** [comment]
Tried this package and it works great, but I need some basic scopes. 

As far as I understand it: if you write a custom search aspect I am all by myself and have to take care of writing all the queries ($term, in the example seems to just be passed along). 

I see the point of custom aspects if I have only one or two exceptions, but if I need scopes to all my models this get cumbersome. Is think just a basic filter/scope would be fantastic.

Anyway, just my two cents. Thanks for all your hard work! 👍

**Comment by AshDev98** [comment]
is there any way to use where method or conditions? I got stuck to filter out some data. Can anyone help me out?
I have attached my code here.
```
<?php

namespace App\Http\Livewire\SuperAdmin;

use Livewire\Component;
use Spatie\Searchable\Search;
use App\Models\Category;

class SuperAdminSearch extends Component
{
    public $query;
    public $searchResults = [];
    public $name = [];

    public function updated($property) {
        $this->name = $this->categoryName();
        if($property == 'query') {
            $searchterm = $this->query;
 
            $this->searchResults = (new Search())
                        ->registerModel(Category::class, 'name')
                        ->perform($searchterm);
        }

        if(empty($this->query)) {
            $this->searchResults = [];
        }
    }


    public function render()
    {
        return view('livewire.super-admin.super-admin-search');
    }
}
```
my model:

```
protected $fillable = ['name', 'category_type'];
public function getSearchResult(): SearchResult
{
    $url = route('super_admin_category_details', $this->id);

    return new SearchResult(
        $this,
        $this->name,
        $url
    );
}
```

In my category table there is 2 fields name and category_type. I just want to search name with the category_type 'ADVERTISEMENT'. But I don’t get any way though.
