### ISSUE TITLE
Compound search

### ISSUE THREAD

**Issue by marcelloinfoweb** [spatie/laravel-searchable#98]
I am using addExactSearchableAttribute, but the result is not exact, if I search for "Marcelo Caetano", in the field that does not have "Marcelo", the result brings "Caetano" with other names.

Would it be possible to only bring the result that contains all the words?

**Comment by stillflame** [comment]
#61 This seems to solve the issue for me.

**Comment by marcelloinfoweb** [comment]
Unfortunately it didn't work, by name it doesn't return anything, just by email. It could be with quotes, if you want with compound words.

**Comment by marcelloinfoweb** [comment]
Thanks!
